### ISSUE TITLE
Native UI Dialog Device selector does not show up when using Cordova but works when launching from xcode

### ISSUE THREAD

**Issue by smenchions** [soltius/BluetoothClassicSerial#1]
Hi,

Love your work on this plugin. 

If we use the following js in our Cordova app and build and deploy the app from cordova to our iPad, the native dialog to select the BT accessory does not show up

bluetoothClassicSerial.discoverUnpaired(function(devices) {
    devices.forEach(function(device) {
        console.log(device.id);
    })
}, failure);

Instead the JS error comes back "Device selection failed." No native dialog picker shows up in our app.

Now, using Xcode, we open the native xCode project file that Cordova built and deployed on our iPad.  We make no changes to the project at all from xCode and simply deploy the project from xCode to our iPad.

Now, the above discoverUnpaired works as expected, showing the native dialog to allow us to select and connect to our unpaired device.

Why does Cordova build/deploy not work, but the xCode build/deploy does work?

Thanks!

Shane

**Comment by kiwisoup** [comment]
Hi Shane,

This plugin is still under very heavy development and not ready for public use.  We've got some more work planned on it in the coming week.  We're in the middle of changing quite a bit of stuff and I won't be testing the build until later in the week.

I'll reply again later in the week once we've have a chance to give it a good shake. 

S.
