### ISSUE TITLE
Cannot read data from headset

### ISSUE THREAD

**Issue by kevinmartinmauro** [soltius/BluetoothClassicSerial#2]
Hey I have been trying for weeks and I can't seem to read any data from the headset that I'm connected to. I can write data just fine, I think, but I'd like to be able to record audio data from my bluetooth headset microphone. 

Any idea on what the challenges might be here in getting this to work? I see that Android has a BluetoothHeadset class, but I'm trying to make changes that will be compatible on both iOS and Android, so anything that can be done at a higher level (i.e. using the write, read, and subscribe commands) would be useful.

I downloaded an HCI packet sniffer, which reads data from the Android logs, to try and figure out what AT commands are being sent. The packet sniffer app has no problems picking up signals when I press a button on the headset, but this library (subscribeRaw) doesn't pick up anything.

**Comment by kevinmartinmauro** [comment]
It seems like I will have to create two channels. This library provides the RFCOM channel for pairing, connection, and opening/closing the second channel. The second channel is a SCO channel. I'm worried whether this will even be possible in iOS, but I am pretty sure it can be done in Android. Please share with me any wisdom you might hive.

**Comment by kiwisoup** [comment]
Hi @kevinmartinmauro,

Thanks for your interest but I'm not in a position to provide any support for this plugin.  It is not intended for use with audio data.  

With regards to RFCOMM data, different devices use different UUIDs so you'll need to know the UUID for the RFCOMM channels (ports) that the device communicates over.  I've been lucky that either the default worked, or the the manufacturer provided the UUID information in their developer material.

Good luck with your project.
